"""Reproduce the Rust full-casefold table with CPython 3.12 / Unicode 15.0.

Only development fixtures use Python; Assistant's runtime reads the generated
Rust constants. No locale-specific lowercasing or partial hand-maintained map.
"""

from pathlib import Path
import sys
import unicodedata


def main() -> None:
    if sys.implementation.name != "cpython" or unicodedata.unidata_version != "15.0.0":
        raise SystemExit("Run with CPython 3.12 (Unicode 15.0.0)")
    rows = []
    for code in range(sys.maxunicode + 1):
        if 0xD800 <= code <= 0xDFFF:
            continue
        character = chr(code)
        folded = character.casefold()
        if folded != character:
            escaped = "".join(f"\\u{{{ord(c):x}}}" for c in folded)
            rows.append(f"    ('\\u{{{code:x}}}', \"{escaped}\"),\n")
    header = (
        "// Generated by scripts/generate_casefold.py using CPython 3.12, Unicode 15.0.0.\n"
        "// Unicode data notice: ../LICENSE-UNICODE.txt (https://www.unicode.org/license.txt).\n"
        "// Complete default full folding: every Unicode scalar whose str.casefold differs.\n"
        "// Regenerate: python3.12 assistant-rs/crates/services/scripts/generate_casefold.py\n"
        "pub(crate) const MAPPINGS: &[(char, &str)] = &[\n"
    )
    destination = Path(__file__).resolve().parents[1] / "src" / "unicode_casefold.rs"
    destination.write_text(header + "".join(rows) + "];\n", encoding="utf-8")


if __name__ == "__main__":
    main()
