"""Nebula 3 headless platform foundations.

This package is deliberately independent from the legacy Qt application.  Importing
it must never initialize a GUI or read legacy global configuration.
"""

from .domain import (
    Advisory,
    AgentAttempt,
    AgentRun,
    Approval,
    Artifact,
    Asset,
    ChatMessage,
    ChatSession,
    Correlation,
    Engagement,
    Evidence,
    Finding,
    Identity,
    KnowledgeSource,
    Observation,
    OperatorProfile,
    ProviderProfile,
    Remediation,
    Report,
    ReportStatus,
    RunEvent,
    ScopePolicy,
    Service,
    SoftwareComponent,
    SourceSnapshot,
    Task,
    ToolCall,
)
from .version import __version__, build_metadata

__all__ = [
    "Advisory",
    "AgentAttempt",
    "AgentRun",
    "Approval",
    "Artifact",
    "Asset",
    "ChatMessage",
    "ChatSession",
    "Correlation",
    "Engagement",
    "Evidence",
    "Finding",
    "Identity",
    "KnowledgeSource",
    "Observation",
    "OperatorProfile",
    "ProviderProfile",
    "Remediation",
    "Report",
    "ReportStatus",
    "RunEvent",
    "ScopePolicy",
    "Service",
    "SoftwareComponent",
    "SourceSnapshot",
    "Task",
    "ToolCall",
    "__version__",
    "build_metadata",
]
