import {expect, test} from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

test("Assistant browser stays read-only through pointer, keyboard and reconnect", async ({page, request}, info) => {
  const headers = {Authorization: "Bearer model-test-token"};
  const origin = String(info.project.use.baseURL);
  const loopback = `http://127.0.0.1:${new URL(origin).port}`;
  const project = await (await request.post("/api/v1/engagements", {headers, data: {name: `Assistant viewer ${info.project.name}`}})).json();
  const scope = await request.put(`/api/v1/engagements/${project.id}/scope`, {headers, data: {allowed_urls: [loopback + "/fixture-site/manual-input"], allowed_ports: [Number(new URL(origin).port)]}});
  expect(scope.ok()).toBeTruthy();
  const prepared = await request.post(`/fixture-site/prepare-viewer/${project.id}`);
  expect(prepared.ok(), await prepared.text()).toBeTruthy();
  const session = await prepared.json();
  const base = `/api/v1/browser-companion/${session.session_id}`;
  const pairing = await (await request.post(loopback + "/api/v1/auth/pairings", {headers, data: {name: "Assistant viewer fixture"}})).json();
  await page.goto(`/#pair=${encodeURIComponent(pairing.secret)}&code=${encodeURIComponent(pairing.confirmation_code)}`);
  await page.getByLabel("Device name").fill("Assistant viewer fixture");
  await page.getByRole("button", {name: "Pair device", exact: true}).click();
  await expect(page.getByRole("button", {name: /Nebula Core (ready|degraded)/})).toBeVisible({timeout: 20000});
  await page.goto(`/projects/${project.id}/workbench?view=browser&browserEngine=managed`);
  const viewer = page.getByRole("region", {name: "Assistant browser", exact: true});
  const image = viewer.getByRole("img", {name: /Assistant browser page — read-only/});
  await expect(image).toBeVisible({timeout: 30000});
  await expect(viewer.getByText(/Read-only view/)).toBeVisible();
  await expect(page.getByLabel("Browser address")).toHaveAttribute("readonly", "");
  expect((await page.getByLabel("Browser address").boundingBox())!.width).toBeGreaterThanOrEqual(Math.min(120, (await viewer.boundingBox())!.width / 3));
  for (const name of ["Go", "New tab", "Close tab", "Pick element", "Select region"]) await expect(viewer.getByRole("button", {name, exact: true})).toHaveCount(0);
  const capture = async () => {
    const response = await request.post(base + "/operations", {headers, data: {operation: "capture", tab_id: session.active_tab_id}});
    expect(response.ok(), await response.text()).toBeTruthy();
    return (await response.json()).text;
  };
  const before = await capture();
  expect(before).toContain("Click fixture");
  const point = await image.evaluate((img: HTMLImageElement) => ({x: 120 * img.clientWidth / img.naturalWidth, y: 80 * img.clientHeight / img.naturalHeight}));
  if (info.project.use.isMobile) await image.tap({position: point}); else await image.click({position: point});
  await page.keyboard.type("Must not reach the page");
  await image.dispatchEvent("wheel", {deltaY: 100});
  expect(await capture()).toBe(before);
  expect((await request.post(base + "/operations", {headers, data: {operation: "navigate", url: loopback}})).status()).toBe(403);
  const closeCode = await page.evaluate(({base, tab}) => new Promise<number>((resolve, reject) => {
    const ws = new WebSocket(`${location.origin.replace(/^http/, "ws")}${base}/tabs/${tab}/stream`, "nebula.browser.v1");
    const timer = setTimeout(() => {ws.close(); reject(new Error("Viewer input was not rejected"));}, 10000);
    ws.onopen = () => ws.send(JSON.stringify({kind: "text", text: "Must not reach the page"}));
    ws.onclose = event => {clearTimeout(timer); resolve(event.code);};
  }), {base, tab: session.active_tab_id});
  expect(closeCode).toBe(4403);
  expect(await capture()).toBe(before);
  await viewer.getByRole("button", {name: "Reconnect view", exact: true}).click();
  await expect(image).toBeVisible();
  await expect(viewer.getByRole("status")).toContainText("Assistant paused");
  await viewer.getByRole("button", {name: "Resume assistant control", exact: true}).click();
  await expect(viewer.getByRole("button", {name: "Stop assistant control", exact: true})).toBeEnabled();
  await viewer.getByRole("button", {name: "Stop assistant control", exact: true}).click();
  expect(await capture()).toBe(before);
  expect((await new AxeBuilder({page}).include(".managed-assistant-browser").analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({path: info.outputPath("assistant-browser-read-only.png")});
});
