import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

test("catch-up refresh icon recovers read state with a compact accessible target", async ({ page, request }, info) => {
  const origin = `http://127.0.0.1:${new URL(String(info.project.use.baseURL)).port}`;
  const pairing = await (await request.post(`${origin}/api/v1/auth/pairings`, { headers: { Authorization: "Bearer model-test-token" }, data: { name: "Catch-up icon test" } })).json();
  await page.goto(`/#pair=${encodeURIComponent(pairing.secret)}&code=${encodeURIComponent(pairing.confirmation_code)}`);
  await page.getByLabel("Device name").fill("Catch-up icon test");
  await page.getByRole("button", { name: "Pair device", exact: true }).click();
  await expect(page.getByRole("button", { name: /Nebula Core (ready|degraded)/ })).toBeVisible({ timeout: 20000 });
  const route = "**/api/v1/chat/sessions/recovery-chat/catch-up?*";
  await page.route(route, r => r.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ detail: "Fixture connection interrupted" }) }));
  await page.goto("/projects/recovery-project/workbench?view=chat&session=recovery-chat");
  const button = page.getByRole("button", { name: "Reload catch-up", exact: true });
  await expect(button).toBeVisible();
  await expect(button).toHaveText("");
  await expect(button).toHaveAttribute("title", "Reload catch-up");
  const size = await button.boundingBox();
  expect(size!.width).toBeGreaterThanOrEqual(44);
  expect(size!.width).toBeLessThanOrEqual(48);
  expect(size!.height).toBeGreaterThanOrEqual(44);
  const notice = page.locator(".chat-recovery-notice").filter({ has: button });
  const copy = await notice.locator("p").boundingBox();
  expect(size!.x).toBeGreaterThanOrEqual(copy!.x + copy!.width);
  await expect(notice).toContainText("Pending actions remain available");
  expect((await new AxeBuilder({ page }).include(".chat-recovery-notice").analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: info.outputPath("catch-up-icon.png"), fullPage: true });
  await page.unroute(route);
  const recovered = page.waitForResponse(r => r.url().includes("/recovery-chat/catch-up?") && r.status() === 200);
  await button.focus();
  await expect(button).toBeFocused();
  await button.press("Enter");
  await recovered;
  await expect(button).toHaveCount(0);
  await page.reload();
  await expect(page.getByText("Saved response after partial workspace searches.")).toBeVisible();
  await expect(button).toHaveCount(0);
});
