import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

test("warm chat adopts acknowledged host mode without losing its conversation", async ({ page, request }, info) => {
  const origin = `http://127.0.0.1:${new URL(String(info.project.use.baseURL)).port}`;
  const headers = { Authorization: "Bearer model-test-token" };
  const start = await request.post(`${origin}/fixture/start`);
  expect(start.ok(), await start.text()).toBe(true);
  const fixture = await start.json();
  const pairing = await (await request.post(`${origin}/api/v1/auth/pairings`, { headers, data: { name: "Host rollover fixture" } })).json();
  await page.goto(`/#pair=${encodeURIComponent(pairing.secret)}&code=${encodeURIComponent(pairing.confirmation_code)}`);
  const deviceName = `Host rollover ${fixture.chat}`;
  await page.getByLabel("Device name").fill(deviceName);
  await page.getByRole("button", { name: "Pair device", exact: true }).click();
  await expect(page.getByRole("button", { name: /Nebula Core (ready|degraded)/ })).toBeVisible({ timeout: 20000 });
  const devices = await (await request.get(`${origin}/api/v1/auth/devices`, { headers })).json();
  const deviceId = devices.find((device: { name: string }) => device.name === deviceName).id;
  const path = `${origin}/api/v1/engagements/${fixture.project}/automation-policy`;
  await page.goto(`/projects/${fixture.project}/workbench?view=chat&session=${fixture.chat}`);
  await expect(page.getByText("Harness answer for Remember this fixture", { exact: true })).toBeVisible();
  const openPolicy = async () => {
    await page.getByRole("button", { name: "Search pages, actions, and settings" }).click();
    await page.getByRole("textbox", { name: "Search pages, actions, and settings" }).fill("network ports");
    await page.getByRole("option", { name: /Project policy and network scope/ }).click();
  };
  await openPolicy();
  const mode = page.getByRole("combobox", { name: "Project execution mode" });
  await expect(mode).toHaveValue("docker");
  await mode.selectOption("host");
  await page.getByRole("checkbox", { name: /Allow host filesystem and network access/ }).check();
  await page.getByRole("button", { name: "Save runtime policy" }).click();
  await expect(page.getByRole("status").filter({ hasText: "Runtime policy updated" })).toBeVisible();
  const savedPolicy = await (await request.get(path, { headers })).json();
  expect(savedPolicy).toMatchObject({ execution_mode: "host", host_access_acknowledged: true });
  await page.reload();
  await openPolicy();
  await expect(mode).toHaveValue("host");
  await expect(page.getByRole("checkbox", { name: /Allow host filesystem and network access/ })).toBeChecked();
  await page.goto(`/projects/${fixture.project}/workbench?view=chat&session=${fixture.chat}`);
  await page.getByRole("textbox", { name: "Message the analyst assistant" }).fill("Continue with host tools");
  await page.getByRole("button", { name: "Send message", exact: true }).click();
  const status = page.locator(".chat-composer > .harness-status-rail");
  await expect(status).toContainText("Working", { timeout: 20000 });
  await expect(status).toContainText("1/3 plan steps");
  const composer = (await page.locator(".chat-composer").boundingBox())!;
  const strip = (await status.boundingBox())!;
  expect(Math.abs((strip.x - composer.x) - (composer.x + composer.width - strip.x - strip.width))).toBeLessThanOrEqual(2);
  const expand = status.getByRole("button", { name: "Expand plan steps, 1 of 3 completed" });
  expect((await expand.boundingBox())!.height).toBeGreaterThanOrEqual(44);
  await expand.click();
  await expect(status.getByRole("list", { name: "Plan steps" })).toBeVisible();
  await status.getByRole("button", { name: "Collapse plan steps, 1 of 3 completed" }).click();
  expect((await new AxeBuilder({ page }).include(".harness-status-rail").analyze()).violations).toEqual([]);
  await expect(status).toHaveCSS("border-top-width", "0px");
  await expect(page.locator(".chat-operator-updates > .harness-status-rail")).toHaveCount(0);
  await page.reload();
  await expect(status).toContainText("Working", { timeout: 20000 });
  expect(await (await request.get(path, { headers })).json()).toEqual(savedPolicy);
  await page.screenshot({ path: info.outputPath("working-in-composer.png"), fullPage: true });
  await request.post(`${origin}/fixture/finish`);
  await expect(status).toHaveCount(0, { timeout: 20000 });
  await expect(page.getByText("Harness answer for Continue with host tools", { exact: true })).toBeVisible({ timeout: 20000 });
  const chatResponse = await request.get(`${origin}/api/v1/chat-sessions/${fixture.chat}`, { headers });
  expect(chatResponse.ok(), await chatResponse.text()).toBe(true);
  const chat = await chatResponse.json();
  expect(chat.harness_session_id).toBeTruthy();
  expect(chat.harness_session_id).not.toBe(fixture.session);
  const sessionResponse = await request.get(`${origin}/api/v1/harness-sessions/${chat.harness_session_id}`, { headers });
  expect(sessionResponse.ok(), await sessionResponse.text()).toBe(true);
  const session = await sessionResponse.json();
  expect(session.metadata.runtime_rollover_reason).toBe("command_runtime_changed");
  expect(session.metadata.command_runtime_snapshot.specs.run_command.description).toMatch(/host/i);
  await page.reload();
  await expect(page.getByText("Harness answer for Continue with host tools", { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: info.outputPath("host-continuation.png"), fullPage: true });
  const catchChat = (await (await request.post(`${origin}/fixture/catch-up`)).json()).chat;
  const cursorPath = `${origin}/api/v1/chat/sessions/${catchChat}`;
  const cursor = await request.put(`${cursorPath}/read-cursor`, { headers, data: { device_id: deviceId, expected_revision: 0, through_at: "2000-01-01T00:00:00Z" } });
  expect(cursor.ok(), await cursor.text()).toBe(true);
  await page.goto(`/projects/${fixture.project}/workbench?view=chat&session=${catchChat}`);
  const catchUp = page.getByRole("region", { name: "Catch up on this conversation" });
  await expect(catchUp).toBeVisible();
  const dismiss = catchUp.getByRole("button", { name: "Dismiss catch-up" });
  await expect(dismiss).toHaveText("");
  await expect(dismiss.locator("svg.lucide-x")).toHaveCount(1);
  expect((await dismiss.boundingBox())!.height).toBeGreaterThanOrEqual(44);
  const item = catchUp.locator("li button").first();
  if (info.project.use.hasTouch) await item.tap();
  else { await item.focus(); await item.press("Enter"); }
  await expect(catchUp).toHaveCount(0);
  const afterRead = await (await request.get(`${cursorPath}/catch-up?device_id=${encodeURIComponent(deviceId)}`, { headers })).json();
  expect(afterRead.items).toEqual([]);
  await page.reload();
  await expect(page.getByText("Harness answer for Catch-up fixture update", { exact: true })).toBeVisible();
  await expect(catchUp).toHaveCount(0);

});
