import { useEffect, useRef, useState } from "react";
import type { ApiClient } from "../api/client";
import { logCaughtDiagnostic } from "../diagnostics";
export interface DecisionSeed {messageId: string; text: string; selection: string}
interface Decision {id: string; revision: number; kind: string; text: string; status: string; scope: string; source_message_id?: string; source_session_id?: string; history: {revision: number; text: string; kind: string; status: string}[]; copied_from_id?: string; copied_from_revision?: number}
export function ChatDecisions({api, sessionId, seed, onSeedConsumed, onMessage}: {api: ApiClient; sessionId: string; seed?: DecisionSeed; onSeedConsumed: () => void; onMessage: (id: string, sessionId?: string) => void}) {
  const [items, setItems] = useState<Decision[]>([]); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
  const seedSeen = useRef(seed);
  const [editor, setEditor] = useState<{id: string; revision: number; text: string; kind: string; source_message_id?: string; source_selection?: string} | undefined>(() => seed ? {id: `decision-${Date.now()}-${Math.random().toString(36).slice(2)}`, revision: 0, text: seed.text.slice(0, 4000), kind: "decision", source_message_id: seed.messageId, source_selection: seed.selection} : undefined);
  const path = `chat/sessions/${encodeURIComponent(sessionId)}/decisions`;
  const reload = async () => {const rows = await api.request<Decision[]>(path); setItems(rows);};
  const run = async (operation: () => Promise<void>) => {setError(undefined); setBusy(true); try {await operation();} catch (e) {void logCaughtDiagnostic("interface.assistant_chat.decisions_failed", "Operator context could not be saved or read.", e, "assistant_chat"); setError(`${e instanceof Error ? e.message : "Decision update failed"}. Reload the saved entries and reapply your edit; the editor is retained.`);} finally {setBusy(false);}};
  useEffect(() => {const controller = new AbortController(); void api.request<Decision[]>(path, {signal: controller.signal}).then(setItems).catch(e => {if (!controller.signal.aborted) {void logCaughtDiagnostic("interface.assistant_chat.decisions_read_failed", "Saved operator context could not be read.", e, "assistant_chat"); setError(e instanceof Error ? e.message : "Could not read decisions");}}); return () => controller.abort();}, [api, path]);
  const newId = () => `decision-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  useEffect(() => {if (seed) {if (seedSeen.current !== seed) setEditor({id: newId(), revision: 0, text: seed.text.slice(0, 4000), kind: "decision", source_message_id: seed.messageId, source_selection: seed.selection}); seedSeen.current = seed; onSeedConsumed();}}, [seed]);
  const change = (item: Decision, action: string) => run(async () => {await api.request(`${path}/${encodeURIComponent(item.id)}`, {method: "PUT", body: JSON.stringify({expected_revision: item.revision, action})}); await reload();});
  const active = items.filter(item => item.status === "active");
  return <section className="chat-decisions" aria-label="Saved decisions and constraints"><header><h3>Decisions and constraints</h3><button className="button quiet" type="button" onClick={() => setEditor({id: newId(), revision: 0, text: "", kind: "decision"})}>Add operator context</button></header><p>Active entries are included in future turns. Editing them does not change a submitted turn. Assumptions remain unresolved until you revise them.</p>{active.length > 1 && <p>Review these entries together. Conflicting instructions remain visible for you to resolve; none is silently preferred.</p>}{error && <div role="alert"><p>{error}</p><button className="button quiet" type="button" onClick={() => void run(async () => {await reload(); if (editor?.revision) {const rows = await api.request<Decision[]>(path); const current = rows.find(row => row.id === editor.id); if (current) setEditor(value => value ? {...value, revision: current.revision} : value);}})}>Reload saved entries</button></div>}{busy && <p role="status">Saving or reading decisions…</p>}{!active.length && !busy && <p>No binding context saved. Model prose is never promoted automatically.</p>}
    {active.map(item => <article key={item.id}><strong>{item.kind} · {item.scope} · revision {item.revision}</strong><p>{item.text}</p>{item.source_message_id && <button className="button quiet" type="button" onClick={() => onMessage(item.source_message_id!, item.source_session_id)}>Source message</button>}{item.copied_from_id && <small>Copied from revision {item.copied_from_revision}; original provenance retained.</small>}<div><button className="button quiet" type="button" disabled={busy} onClick={() => setEditor({...item})}>Edit decision</button><button className="button quiet" type="button" disabled={busy} onClick={() => void change(item, "supersede")}>Supersede</button><button className="button quiet" type="button" disabled={busy} onClick={() => void change(item, "remove")}>Remove decision</button>{item.scope === "conversation" && <button className="button quiet" type="button" disabled={busy} onClick={() => void change(item, "promote")}>Promote to project</button>}</div>{item.history.length > 0 && <details><summary>Revision history</summary>{item.history.map(row => <p key={row.revision}>Revision {row.revision} · {row.status} · {row.text}</p>)}</details>}</article>)}
    {editor && <div className="decision-editor"><label>Context type<select value={editor.kind} onChange={event => setEditor({...editor, kind: event.target.value})}><option value="decision">Decision</option><option value="constraint">Constraint</option><option value="assumption">Unresolved assumption</option></select></label><label>Operator context<textarea aria-label="Operator context text" maxLength={4000} value={editor.text} onChange={event => setEditor({...editor, text: event.target.value})} /></label><small>{editor.text.length}/4000 characters · {editor.revision ? "Edit future turns" : "Conversation scope"}</small>{editor.source_selection && <details><summary>Original selected text</summary><pre>{editor.source_selection}</pre></details>}<button className="button primary" type="button" disabled={busy || !editor.text.trim()} onClick={() => void run(async () => {await api.request(`${path}/${encodeURIComponent(editor.id)}`, {method: "PUT", body: JSON.stringify({...editor, expected_revision: editor.revision, action: "save"})}); setEditor(undefined); await reload();})}>Save operator context</button><button className="button quiet" type="button" onClick={() => setEditor(undefined)}>Cancel decision edit</button></div>}
    {items.some(item => item.status !== "active") && <details><summary>Superseded and removed entries</summary>{items.filter(item => item.status !== "active").map(item => <article key={item.id}><strong>{item.status} · revision {item.revision}</strong><p>{item.text}</p><details><summary>Revision history</summary>{item.history.map(row => <p key={row.revision}>Revision {row.revision}: {row.text}</p>)}</details></article>)}</details>}
  </section>;
}
