import { useState } from "react";
import type { ApiClient } from "../api/client";
import { logCaughtDiagnostic } from "../diagnostics";
interface Evidence {message_id: string; retrieved: {source_id: string; chunk_id: string; name: string; excerpt: string; page?: number}[]; observations: {id: string; kind: string; label: string; status?: string; summary?: string; receipt?: Record<string, unknown>; evidence_ids?: string[]}[]; artifacts: {id: string; kind: string; label: string}[]; limitations: string[]}
export function ChatEvidence({api, sessionId, messageId, onResults}: {api: ApiClient; sessionId: string; messageId: string; onResults: () => void}) {
  const [value, setValue] = useState<Evidence>(); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
  const read = async () => {if (busy) return; setBusy(true); setError(undefined); try {setValue(await api.request<Evidence>(`chat/sessions/${encodeURIComponent(sessionId)}/messages/${encodeURIComponent(messageId)}/evidence`));} catch(e) {void logCaughtDiagnostic("interface.assistant_chat.evidence_failed", "Supporting evidence could not be read.", e, "assistant_chat"); setError("Could not load recorded support. Retry; the answer remains available.");} finally {setBusy(false);}};
  return <details className="chat-evidence" onToggle={event => {if (event.currentTarget.open && !value && !error) void read();}}><summary>Supporting evidence</summary>{busy && <p role="status">Reading recorded sources…</p>}{error && <div role="alert"><p>{error}</p><button className="button quiet" type="button" onClick={() => void read()}>Retry evidence</button></div>}{value && <><p>The answer is assistant interpretation. The records below show what was retrieved or reported during this turn.</p>{value.retrieved.length > 0 && <section><strong>Retrieved material</strong>{value.retrieved.map(source => <details key={`${source.source_id}:${source.chunk_id}`}><summary>{source.name}{source.page ? ` · page ${source.page}` : ""}</summary><blockquote>{source.excerpt}</blockquote><a href={`/knowledge?source=${encodeURIComponent(source.source_id)}`}>Open source</a><small>Recorded chunk: {source.chunk_id}</small></details>)}</section>}{value.observations.length > 0 && <section><strong>Recorded runtime results</strong>{value.observations.map(item => <details key={item.id}><summary>{item.label} · {item.status ?? item.kind}</summary>{item.summary && <p>{item.summary}</p>}{item.kind === "reported" && <p>Assistant-reported checkpoint; verify its supporting records.</p>}{item.receipt && <><p>Recorded receipt. It describes this operation; it does not validate the whole answer.</p><pre>{JSON.stringify(item.receipt, null, 2)}</pre></>}{Boolean(item.evidence_ids?.length) && <p>Evidence references: {item.evidence_ids?.join(", ")}</p>}</details>)}</section>}{value.artifacts.length > 0 && <section><strong>Retained artifacts</strong>{value.artifacts.map(item => <p key={item.id}>{item.label} · {item.kind}</p>)}</section>}{value.limitations.map((text, index) => <p className="evidence-limitation" key={index}>{text}</p>)}<button className="button quiet" type="button" onClick={onResults}>Inspect retained results</button></>}</details>;
}
