import { useState } from "react";
import type { useChatQueue, QueueItem } from "../pages/useChatQueue";
export function ChatQueuePanel({queue: controller, onRefreshConversation}: {queue: ReturnType<typeof useChatQueue>; onRefreshConversation: () => void}) {
  const {queue, busy, error, mutate, reload} = controller;
  const [editing, setEditing] = useState<QueueItem>(); const [text, setText] = useState("");
  const items = queue?.items.filter(item => !["complete", "cancelled"].includes(item.status)) ?? [];
  const editable = items.filter(item => ["queued", "needs_review"].includes(item.status));
  const move = (item: QueueItem, direction: number) => { const order = editable.map(row => row.id); const index = order.indexOf(item.id); const target = index + direction; if (target < 0 || target >= order.length) return; [order[index], order[target]] = [order[target], order[index]]; void mutate({action: "reorder", order}); };
  if (!items.length && !error && !editing) return null;
  return <section className="chat-follow-up-queue" aria-label="Core follow-up queue">
    {(items.length > 0 || error) && <><header><strong>Follow-ups · {queue?.paused ? "Paused" : "Core dispatches in order"}</strong><button type="button" disabled={busy} onClick={() => void mutate({action: queue?.paused ? "resume" : "pause"})}>{queue?.paused ? "Resume queue" : "Pause queue"}</button><button type="button" disabled={busy} onClick={() => void mutate({action: "clear"})}>Clear queue</button></header><p>Explicitly queued work continues after all browser tabs close.</p></>}
    {error && <div role="alert"><p>{error}</p><button type="button" onClick={() => void reload()}>Reload queue</button></div>}
    <ol>{items.map((item, index) => <li key={item.id}><div><strong>{index + 1}. {item.status.replaceAll("_", " ")}</strong><p>{item.request.messages[0]?.content}</p>{Boolean(item.request.context_attachments?.length) && <small>{item.request.context_attachments?.length} selected context attachment(s)</small>}{item.detail && <p>{item.detail}</p>}{item.turn_id && <button type="button" onClick={onRefreshConversation}>Inspect conversation</button>}</div>{["queued", "needs_review"].includes(item.status) && <div><button type="button" disabled={busy} onClick={() => {setEditing(item); setText(item.request.messages[0]?.content ?? "");}}>Edit queued message {index + 1}</button><button type="button" disabled={busy || editable.indexOf(item) === 0} onClick={() => move(item, -1)} aria-label={`Move message ${index + 1} up`}>↑</button><button type="button" disabled={busy || editable.indexOf(item) === editable.length - 1} onClick={() => move(item, 1)} aria-label={`Move message ${index + 1} down`}>↓</button>{item.status === "needs_review" && <button type="button" disabled={busy} onClick={() => void mutate({action: "retry", item_id: item.id})}>Retry as new message</button>}<button type="button" disabled={busy} onClick={() => void mutate({action: "remove", item_id: item.id})}>Remove</button></div>}</li>)}</ol>
    {editing && <div><label>Queued message<textarea aria-label="Edit queued text" value={text} onChange={event => setText(event.target.value)} /></label><p>Attachments and runtime options stay attached. Changes apply only before dispatch.</p><button type="button" disabled={busy || !text.trim()} onClick={() => void (async () => {if (await mutate({action: "edit", item_id: editing.id, request: {...editing.request, messages: [{...editing.request.messages[0], role: "user", content: text, content_blocks: [{type: "text", text}, ...(editing.request.messages[0]?.content_blocks ?? []).filter(block => block.type !== "text")]}]}})) setEditing(undefined);})()}>Save queued edit</button><button type="button" onClick={() => setEditing(undefined)}>Cancel edit</button></div>}
  </section>;
}
