#!/usr/bin/env python3
"""Generate the Core-offline TypeScript remediation catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/nebula/v3/diagnostic_guidance.json"
DESTINATION = ROOT / "ui/src/diagnostics/catalog.generated.ts"


def rendered() -> str:
    catalog = json.loads(SOURCE.read_text(encoding="utf-8"))
    encoded = json.dumps(catalog, indent=2, ensure_ascii=False)
    return (
        "// Generated by scripts/generate_diagnostic_catalog.py. Do not edit.\n"
        f"export const diagnosticRemediationCatalog = {encoded} as const;\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = rendered()
    if args.check:
        return (
            0
            if DESTINATION.exists()
            and DESTINATION.read_text(encoding="utf-8") == expected
            else 1
        )
    DESTINATION.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
