#!/usr/bin/env node
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const source = path.resolve(process.argv[2] ?? "");
if (!process.argv[2]) throw new Error("usage: node scripts/import_icon_pack.mjs <extracted nebula-icon-pack>");

const checksums = new Map(readFileSync(path.join(source, "SHA256SUMS.txt"), "utf8").trim().split("\n").map(line => {
  const [hash, file] = line.trim().split(/\s+/, 2);
  return [file, hash];
}));
const names = [...checksums.keys()].filter(file => file.startsWith("regular/") && file.endsWith(".svg"))
  .map(file => path.basename(file, ".svg")).sort();
if (names.length !== 167) throw new Error(`expected 167 mapped icons, found ${names.length}`);

const readSvg = (weight, name) => {
  const relative = `${weight}/${name}.svg`;
  const bytes = readFileSync(path.join(source, relative));
  const actual = createHash("sha256").update(bytes).digest("hex");
  if (checksums.get(relative) !== actual) throw new Error(`checksum mismatch: ${relative}`);
  const svg = bytes.toString("utf8").trim();
  const body = svg.replace(/^<svg\b[^>]*>/, "").replace(/<\/svg>$/, "");
  if (body === svg) throw new Error(`invalid SVG wrapper: ${relative}`);
  return body.replaceAll(/id="([^"]+)"/g, 'id="__NEBULA_ICON_ID__$1"')
    .replaceAll(/url\(#([^)]+)\)/g, "url(#__NEBULA_ICON_ID__$1)");
};

const rows = names.map(name => `export const ${name} = createIcon(${JSON.stringify(name)}, ${JSON.stringify(readSvg("regular", name))}, ${JSON.stringify(readSvg("light", name))});`);
const output = `// Generated by scripts/import_icon_pack.mjs. Do not edit by hand.\nimport { createIcon } from "./factory";\n\n${rows.join("\n")}\n`;
const target = path.resolve("ui/src/icons/generated.tsx");
mkdirSync(path.dirname(target), { recursive: true });
writeFileSync(target, output);
console.log(`wrote ${names.length} verified icons to ${target}`);
