"""Regenerate src/nebula/v3/known_model_limits.py from OpenRouter's public catalog.

Usage:
    python3 scripts/refresh_known_model_limits.py [catalog.json]

Without an argument the catalog is fetched from https://openrouter.ai/api/v1/models.
Each model uses the smaller of OpenRouter's aggregate and primary-route context
length, so a first-party API is never credited with a larger window than its
main route serves. FIRST_PARTY_OVERRIDES then corrects models whose direct API
limits differ from OpenRouter's (or that OpenRouter no longer lists).
"""

from __future__ import annotations

import json
import sys
import urllib.request
from datetime import date
from pathlib import Path

CATALOG_URL = "https://openrouter.ai/api/v1/models"
OUTPUT = Path(__file__).resolve().parents[1] / "src/nebula/v3/known_model_limits.py"

VENDORS = {
    "amazon",
    "anthropic",
    "baidu",
    "bytedance-seed",
    "cohere",
    "deepseek",
    "google",
    "meta-llama",
    "microsoft",
    "minimax",
    "mistralai",
    "moonshotai",
    "nvidia",
    "openai",
    "qwen",
    "tencent",
    "x-ai",
    "xiaomi",
    "z-ai",
}

# (context_window, max_output_tokens or None) from first-party documentation.
FIRST_PARTY_OVERRIDES: dict[str, tuple[int, int | None]] = {
    # Anthropic: Sonnet 4 / 4.5 serve 1M only with a beta header Nebula does not send.
    "claude-sonnet-4": (200_000, 64_000),
    "claude-sonnet-4-5": (200_000, 64_000),
    "claude-3-opus": (200_000, 4_096),
    "claude-3-5-haiku": (200_000, 8_192),
    "claude-3-5-sonnet": (200_000, 8_192),
    "claude-3-7-sonnet": (200_000, 64_000),
    # DeepSeek API names (api-docs.deepseek.com). The legacy chat/reasoner
    # aliases keep their historical 128K API window as a conservative floor.
    "deepseek-flash": (1_048_576, 384_000),
    "deepseek-chat": (131_072, 8_192),
    "deepseek-reasoner": (131_072, 65_536),
    # Google models OpenRouter no longer lists.
    "gemini-1-5-flash": (1_048_576, 8_192),
    "gemini-1-5-pro": (2_097_152, 8_192),
    "gemini-2-0-flash": (1_048_576, 8_192),
    # xAI models OpenRouter no longer lists.
    "grok-3": (131_072, None),
    "grok-4": (256_000, None),
}


def normalize(model_id: str) -> str:
    return model_id.strip().lower().replace(".", "-").replace("_", "-")


def positive(value: object) -> int | None:
    return value if type(value) is int and value > 0 else None


def build(payload: dict) -> dict[str, tuple[int, int | None]]:
    limits: dict[str, tuple[int, int | None]] = {}
    for item in payload["data"]:
        identity = item.get("id")
        if not isinstance(identity, str) or ":" in identity or "/" not in identity:
            continue
        vendor, slug = identity.split("/", 1)
        if vendor not in VENDORS:
            continue
        top = item.get("top_provider") or {}
        windows = [
            value
            for value in (
                positive(item.get("context_length")),
                positive(top.get("context_length")),
            )
            if value
        ]
        if not windows:
            continue
        window = min(windows)
        output = positive(top.get("max_completion_tokens"))
        if output is not None and output >= window:
            output = None
        key = normalize(slug)
        if key in limits:
            # Two catalog ids collapse to one key: keep the conservative pair.
            previous_window, previous_output = limits[key]
            window = min(window, previous_window)
            outputs = [value for value in (output, previous_output) if value]
            output = min(outputs) if outputs else None
        limits[key] = (window, output)
    limits.update(FIRST_PARTY_OVERRIDES)
    return dict(sorted(limits.items()))


def render(limits: dict[str, tuple[int, int | None]]) -> str:
    lines = [
        '"""Published context limits for well-known hosted models.',
        "",
        "Generated by scripts/refresh_known_model_limits.py from OpenRouter's public",
        "model catalog plus first-party corrections; do not edit by hand.",
        '"""',
        "",
        f'KNOWN_MODEL_LIMITS_REVISION = "{date.today().isoformat()}"',
        "",
        "# normalized model id -> (context_window, max_output_tokens or None)",
        "KNOWN_MODEL_LIMITS: dict[str, tuple[int, int | None]] = {",
    ]
    lines.extend(
        f'    "{key}": ({window}, {output}),'
        for key, (window, output) in limits.items()
    )
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    if len(sys.argv) > 1:
        payload = json.loads(Path(sys.argv[1]).read_text())
    else:
        with urllib.request.urlopen(CATALOG_URL, timeout=30) as response:
            payload = json.load(response)
    limits = build(payload)
    OUTPUT.write_text(render(limits))
    print(f"wrote {len(limits)} models to {OUTPUT}")


if __name__ == "__main__":
    main()
