[package]
name = "nebula-assistant-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "BSD-3-Clause AND Unicode-3.0"
publish.workspace = true

[dependencies]
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
jsonschema.workspace = true
sha2.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
speedate.workspace = true
strum.workspace = true
idna.workspace = true

[lints]
workspace = true
